#!/bin/sh

JSDIR=$HOME/.js
FILE=github.com.js
SRC=$(pwd)/$FILE
DEST=$JSDIR/$FILE

if [ ! $(which coffee) ]; then
  echo "Requirements: coffee"
  exit
fi

touch $SRC

if [ -e $DEST ]; then
  echo "Already exists: $DEST."
  echo "Aborting in case it's an existing dotjs file."
  exit

else
  if [ ! -e $JSDIR ]; then
    mkdir $JSDIR
  fi

  ln -s $SRC $DEST
fi
